Repository tezos-reward-distributor-organization/tezos-reward-distributor, pull requests merged in 2019-11, with the labels that each got.

#127 Integrate TzStats and sphinx documentation
  .gitignore
  .travis.yml
  docs/Makefile
  docs/conf.py
  docs/configuration.rst
  docs/contributers.rst
  docs/index.rst
  docs/installation.rst
  docs/run.rst
  readme.md
  src/api/provider_factory.py
  src/exception/tzscan.py
  src/exception/tzstats.py
  src/launch_common.py
  src/main.py
  src/pay/payment_producer.py
  src/rpc/rpc_reward_api.py
  src/tzscan/tzscan_block_api.py
  src/tzscan/tzscan_mirror_selection_helper.py
  src/tzscan/tzscan_reward_api.py
  src/tzscan/tzscan_reward_provider_helper.py
  src/tzstats/__init__.py
  src/tzstats/tzstats_api_constants.py
  src/tzstats/tzstats_block_api.py
  src/tzstats/tzstats_reward_api.py
  src/tzstats/tzstats_reward_provider_helper.py
Labels: documentation, enhancement

#132 Fix tzstats and destination map issues
  src/calc/phased_payment_calculator.py
  src/pay/batch_payer.py
  src/pay/payment_producer.py
  src/rpc/rpc_reward_api.py
  src/tzstats/tzstats_api_constants.py
  src/tzstats/tzstats_reward_api.py
  src/tzstats/tzstats_reward_provider_helper.py
  src/util/csv_payment_file_parser.py
Labels: bug, enhancement

#133 Improve Logging and reporting reward calculations (#8)
  src/pay/payment_producer.py
Labels: enhancement

#134 add provider arg to configure
  src/configure.py
Labels: bug
