Repository tezos-reward-distributor-organization/tezos-reward-distributor, pull requests merged in 2020-09, with the labels that each got.

#243 Introduce PEP8 code formatting
  .travis.yml
  docs/contributors.rst
  src/Constants.py
  src/NetworkConfiguration.py
  src/api/provider_factory.py
  src/calc/calculate_phase2.py
  src/calc/calculate_phase3.py
  src/calc/calculate_phase4.py
  src/calc/calculate_phase5.py
  src/calc/calculate_phase6.py
  src/calc/calculate_phase7.py
  src/calc/calculate_phase_base.py
  src/calc/calculate_phase_final.py
  src/calc/test_calculatePhase0.py
  src/calc/test_calculatePhase1.py
  src/calc/test_calculatePhase3.py
  src/calc/test_calculatePhase4.py
  src/calc/test_calculatePhase5.py
  src/cli/simple_client_manager.py
  src/cli/test_walletClientManager.py
  src/cli/wallet_client_manager.py
  src/config/addr_type.py
  src/config/test_BakingYamlConfParser.py
  src/config/test_yamlConfParser.py
  src/config/yaml_baking_conf_parser.py
  src/config/yaml_conf_parser.py
  src/configure.py
  src/emails/email_manager.py
  src/exception/api_provider.py
  src/exception/client.py
  src/launch_common.py
  src/log_config.py
  src/main.py
  src/model/baking_conf.py
  src/model/reward_log.py
  src/model/reward_provider_model.py
  src/pay/batch_payer.py
  src/pay/payment_consumer.py
  src/pay/payment_producer.py
  src/pay/payment_producer_abc.py
  src/pay_for.py
  src/pytzapi/block.py
  src/retry_failed.py
  src/rpc/rpc_block_api.py
  src/rpc/rpc_reward_api.py
  src/setup.cfg
  src/stats/stats_pusblisher.py
  src/tzstats/tzstats_api_constants.py
  src/tzstats/tzstats_block_api.py
  src/tzstats/tzstats_reward_api.py
  src/tzstats/tzstats_reward_provider_helper.py
  src/util/client_utils.py
  src/util/dir_utils.py
  src/util/fee_validator.py
  src/util/lock_file.py
  src/util/rpc_utils.py
  src/version.py
Labels: enhancement

#256 Missing api_base_url parameter in retry_failed.py
  src/retry_failed.py
Labels: bug

#260 Fix variable to use for balance checking
  src/pay/batch_payer.py
Labels: bug

#258 Adjust staking balance when snapshot index == 15
  src/pay/payment_producer.py
  src/rpc/rpc_reward_api.py
Labels: bug, critical

#264 Fix Anonymous stats
  docs/statistics.rst
  readme.md
  src/Constants.py
  src/main.py
  src/pay/payment_consumer.py
  src/pay/payment_producer.py
  src/stats/stats_publisher.py
  src/stats/stats_pusblisher.py
  src/tzkt/tzkt_api.py
  src/version.py
Labels: documentation

#259 Evaluate PAYMENT_OFFSET at start of each cycle
  src/api/block_api.py
  src/launch_common.py
  src/pay/payment_producer.py
Labels: bug

#267 fix typo, addresses issue #266
  src/main.py
Labels: bug

#268 [Fix] Readme terms tzkt
  docs/index.rst
  readme.md
Labels: documentation

#269 Fix sending to multiple recipients and payment status
  src/emails/email_manager.py
  src/emails/email_worker.py
Labels: bug, critical

#257 Check local node bootstrap status
  src/cli/simple_client_manager.py
  src/pay/payment_producer.py
  src/rpc/rpc_block_api.py
  src/util/rpc_utils.py
Labels: bug

#272 Added payment addresses
  contributor_payments.csv
Labels: documentation

#265 Add a new run mode for retrying payments
  src/Constants.py
  src/launch_common.py
  src/main.py
  src/pay/payment_producer.py
  src/retry_failed.py
Labels: enhancement
