Repository tezos-reward-distributor-organization/tezos-reward-distributor, pull requests merged in 2020-08, with the labels that each got.

#232 TzKT reward & block provider
  .gitignore
  .travis.yml
  src/api/provider_factory.py
  src/config/yaml_baking_conf_parser.py
  src/configure.py
  src/launch_common.py
  src/main.py
  src/pay/payment_producer.py
  src/retry_failed.py
  src/tzkt/__init__.py
  src/tzkt/data/tz1Lhf4J9Qxoe3DZ2nfe8FGDnvVj7oKjnMY6_185_actual.json
  src/tzkt/data/tz1Lhf4J9Qxoe3DZ2nfe8FGDnvVj7oKjnMY6_237_actual.json
  src/tzkt/data/tz1Lhf4J9Qxoe3DZ2nfe8FGDnvVj7oKjnMY6_242_actual.json
  src/tzkt/data/tz1PeZx7FXy7QRuMREGXGxeipb24RsMMzUNe_135_actual.json
  src/tzkt/data/tz1RV1MBbZMR68tacosb7Mwj6LkbPSUS1er1_242_expected.json
  src/tzkt/data/tz1S1Aew75hMrPUymqenKfHo8FspppXKpW7h_233_actual.json
  src/tzkt/data/tz1S8e9GgdZG78XJRB3NqabfWeM37GnhZMWQ_235_expected.json
  src/tzkt/data/tz1UUgPwikRHW1mEyVZfGYy6QaxrY6Y7WaG5_207_actual.json
  src/tzkt/data/tz1V4qCyvPKZ5UeqdH14HN42rxvNPQfc9UZg_220_actual.json
  src/tzkt/data/tz1WnfXMPaNTBmH7DBPwqCWs9cPDJdkGBTZ8_233_expected.json
  src/tzkt/data/tz1WnfXMPaNTBmH7DBPwqCWs9cPDJdkGBTZ8_74_actual.json
  src/tzkt/data/tz1YKh8T79LAtWxX29N5VedCSmaZGw9LNVxQ_246_expected.json
  src/tzkt/data/tz1ZRWFLgT9sz8iFi1VYWPfRYeUvUSFAaDao_201_actual.json
  src/tzkt/data/tz1ZRWFLgT9sz8iFi1VYWPfRYeUvUSFAaDao_232_expected.json
  src/tzkt/data/tz1gk3TDbU7cJuiBRMhwQXVvgDnjsxuWhcEA_135_actual.json
  src/tzkt/test_tzkt_api.py
  src/tzkt/tzkt_api.py
  src/tzkt/tzkt_block_api.py
  src/tzkt/tzkt_reward_api.py
Labels: critical, enhancement

#237 Filter out baker address
  src/rpc/rpc_reward_api.py
Labels: critical

#227 Parse node urls to handle potential tls encryption (resolves #226)
  .gitignore
  src/api/provider_factory.py
  src/cli/simple_client_manager.py
  src/launch_common.py
  src/rpc/rpc_block_api.py
Labels: bug

#250 Add guidelines for rewarding contributions in the context of the TRD grant
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
  CONTRIBUTORS
  contributor_payments.csv
  docs/contributers.rst
  docs/contributors.rst
Labels: documentation

#251 Check the balance of the payout address and warn the user if insufficient
  src/emails/email_manager.py
  src/pay/batch_payer.py
  src/pay/payment_consumer.py
Labels: critical, enhancement
