Repository tezos-reward-distributor-organization/tezos-reward-distributor, pull requests merged in 2020-01, with the labels that each got.

#179 Edit default node url and log CF-RAY unique request id
  src/Constants.py
  src/rpc/rpc_reward_api.py
Labels: enhancement

#168 Hostname, port to client binary call; fix prior Athens issues
  src/NetworkConfiguration.py
  src/cli/simple_client_manager.py
  src/cli/test_walletClientManager.py
  src/cli/wallet_client_manager.py
  src/config/test_BakingYamlConfParser.py
  src/main.py
  src/pay/batch_payer.py
  src/rpc/rpc_reward_api.py
Labels: bug

#181 Support paying burn fee to reactivate zeroed tz1 address
  examples/tz1boot1pK9h2BVGXdyvfQSv8kd1LQM6H889.yaml
  src/calc/calculate_phase0.py
  src/calc/calculate_phase1.py
  src/calc/calculate_phase2.py
  src/calc/calculate_phase3.py
  src/calc/calculate_phase4.py
  src/calc/calculate_phase5.py
  src/calc/calculate_phase6.py
  src/calc/calculate_phase7.py
  src/calc/calculate_phase_base.py
  src/calc/phased_payment_calculator.py
  src/calc/test_calculatePhase0.py
  src/calc/test_calculatePhase1.py
  src/calc/test_calculatePhase2.py
  src/calc/test_calculatePhase3.py
  src/calc/test_calculatePhase4.py
  src/calc/test_calculatePhase5.py
  src/cli/cmd_manager.py
  src/configure.py
  src/main.py
  src/model/baking_conf.py
  src/model/reward_log.py
  src/pay/batch_payer.py
  src/pay/payment_consumer.py
  src/pay/payment_producer.py
  src/pay_for.py
  src/rpc/rpc_reward_api.py
  src/tzstats/tzstats_api_constants.py
  src/tzstats/tzstats_reward_api.py
  src/tzstats/tzstats_reward_provider_helper.py
Labels: enhancement

#183 Update sphinx documentation
  docs/configuration.rst
  docs/contributers.rst
  docs/index.rst
  docs/linuxservice.rst
  docs/paymentaddress.rst
  docs/run.rst
  docs/tezossigner.rst
  docs/tezossignerdocker.rst
  readme.md
Labels: documentation, enhancement

#186 Fix bug and decrease max transactions per batch
  src/calc/calculate_phase6.py
  src/pay/batch_payer.py
Labels: bug

#184 Added rules_map, min_delegation_amt and re-ordered.
  docs/configuration.rst
Labels: documentation
