Repository tezos-reward-distributor-organization/tezos-reward-distributor, pull requests merged in 2020-11, with the labels that each got.

#295 [WIP] Added plugins subsystem
  docs/plugins.md
  examples/tz1boot1pK9h2BVGXdyvfQSv8kd1LQM6H889.yaml
  src/NetworkConfiguration.py
  src/calc/test_calculatePhase0.py
  src/config/test_BakingYamlConfParser.py
  src/config/yaml_baking_conf_parser.py
  src/emails/email_manager.py
  src/emails/email_worker.py
  src/main.py
  src/model/baking_conf.py
  src/pay/batch_payer.py
  src/pay/payment_consumer.py
  src/pay/payment_producer.py
  src/plugins/__init__.py
  src/plugins/email.py
  src/plugins/plugins.py
  src/plugins/telegram.py
  src/plugins/twitter.py
  src/plugins/webhook.py
  src/rpc/rpc_reward_api.py
  src/tzkt/test_tzkt_api.py
Labels: enhancement

#292 Handle 5XX Errors Better
  src/rpc/rpc_reward_api.py
Labels: documentation & logging

#298 Plugins Upgrade Notice
  docs/configuration.rst
  docs/index.rst
  docs/plugins.md
  src/config/test_BakingYamlConfParser.py
  src/config/yaml_baking_conf_parser.py
  src/plugins/plugins.py
Labels: documentation & logging

#277 Add TRD support for Dexter liquidity pool payouts (tzstats)
  .travis.yml
  examples/tz1boot1pK9h2BVGXdyvfQSv8kd1LQM6H889.yaml
  requirements.txt
  src/Dexter/__init__.py
  src/Dexter/dexter_utils.py
  src/api/reward_api.py
  src/calc/test_calculatePhase0.py
  src/config/yaml_baking_conf_parser.py
  src/model/baking_conf.py
  src/pay/payment_producer.py
  src/rpc/rpc_reward_api.py
  src/tzkt/tzkt_api.py
  src/tzkt/tzkt_reward_api.py
  src/tzstats/tzstats_reward_api.py
  src/tzstats/tzstats_reward_provider_helper.py
Labels: critical, enhancement

#301 If supporters_set exists but not set to anything, create empty set
  src/config/test_BakingYamlConfParser.py
  src/config/yaml_baking_conf_parser.py
Labels: bug

#300 Documentation Updates
  docs/conf.py
  docs/configuration.rst
  docs/index.rst
  docs/plugins.md
  docs/tezossigner.rst
  docs/tezossignerdocker.rst
Labels: documentation & logging

#306 Update twitter.py
  src/calc/test_calculatePhase0.py
  src/plugins/twitter.py
Labels: bug

#309 Remove unused variable
  src/calc/calculate_phaseMerge.py
Labels: bug

#302 Minor fixes, release preparation (docs, fees, etc)
  contribution_payment_history.csv
  docs/configuration.rst
  docs/index.rst
  fee.ini
  readme.md
Labels: documentation & logging, enhancement

#313 Update contributors.csv
  contributors.csv
Labels: documentation & logging

#315 [Doc] simplified contribution_payment_histroy.csv for better readability
  contribution_payment_history.csv
Labels: documentation & logging

#318 Removed manual debugging line from Dexter merge
  src/rpc/rpc_reward_api.py
Labels: documentation & logging

#316 Rework exceptions for payment producer loop
  src/pay/payment_producer.py
  src/rpc/rpc_reward_api.py
Labels: bug, critical

#320 Swap pycodestyle for flake8 to include code linting
  .flake8
  .github/pull_request_template.md
  .travis.yml
  src/Dexter/dexter_utils.py
  src/calc/test_calculatePhaseMapping.py
  src/cli/simple_client_manager.py
  src/config/yaml_baking_conf_parser.py
  src/configure.py
  src/pay/payment_consumer.py
  src/plugins/twitter.py
  src/rpc/rpc_reward_api.py
  src/tzkt/tzkt_block_api.py
  src/tzstats/tzstats_block_api.py
  src/tzstats/tzstats_reward_provider_helper.py
Labels: Quality

#322 Check requirements and install missing packages
  .travis.yml
  requirements.txt
  src/main.py
  src/tzstats/tzstats_reward_provider_helper.py
Labels: enhancement

#317 Separate log file for consistent verbose logs, verbose log file archiving, verbose log file per cycle
  src/api/block_api.py
  src/api/provider_factory.py
  src/cli/cmd_manager.py
  src/cli/simple_client_manager.py
  src/cli/wallet_client_manager.py
  src/config/config_parser.py
  src/config/yaml_baking_conf_parser.py
  src/config/yaml_conf_parser.py
  src/configure.py
  src/launch_common.py
  src/log_config.py
  src/main.py
  src/pay/batch_payer.py
  src/pay/payment_consumer.py
  src/pay/payment_producer.py
  src/pay_for.py
  src/plugins/email.py
  src/plugins/plugins.py
  src/plugins/telegram.py
  src/plugins/twitter.py
  src/plugins/webhook.py
  src/rpc/rpc_block_api.py
  src/rpc/rpc_reward_api.py
  src/test_verbose_logging_helper.py
  src/tzkt/test_tzkt_api.py
  src/tzkt/tzkt_api.py
  src/tzkt/tzkt_block_api.py
  src/tzkt/tzkt_reward_api.py
  src/tzstats/tzstats_block_api.py
  src/tzstats/tzstats_reward_api.py
  src/tzstats/tzstats_reward_provider_helper.py
  src/util/client_utils.py
  src/util/rpc_utils.py
  src/verbose_logging_helper.py
Labels: documentation & logging

#325 Issue 296
  src/log_config.py
  src/main.py
  src/pay/batch_payer.py
  src/pay/payment_consumer.py
  src/pay/payment_producer.py
  src/pay_for.py
  src/rpc/rpc_reward_api.py
  src/test_verbose_logging_helper.py
  src/verbose_logging_helper.py
Labels: documentation & logging

#319 More unit tests, introduce Pytest
  .travis.yml
  docs/configuration.rst
  src/Constants.py
  src/NetworkConfiguration.py
  src/api/provider_factory.py
  src/calc/calculate_phaseMerge.py
  src/calc/phased_payment_calculator.py
  src/configure.py
  src/exception/api_provider.py
  src/launch_common.py
  src/model/reward_log.py
  src/pay/double_payment_check.py
  src/pay/payment_consumer.py
  src/pay/payment_producer.py
  src/rpc/rpc_block_api.py
  src/rpc/rpc_reward_api.py
  src/stats/stats_publisher.py
  tests/test_BakingYamlConfParser.py
  tests/test_calculatePhase0.py
  tests/test_calculatePhase1.py
  tests/test_calculatePhase2.py
  tests/test_calculatePhase3.py
  tests/test_calculatePhase4.py
  tests/test_calculatePhaseMapping.py
  tests/test_calculatePhaseMerge.py
  tests/test_phases.py
  tests/test_rpc_api.py
  tests/test_tzkt_api.py
  tests/test_walletClientManager.py
  tests/test_yamlConfParser.py
  tests/tzkt_data/tz1Lhf4J9Qxoe3DZ2nfe8FGDnvVj7oKjnMY6_185_actual.json
  tests/tzkt_data/tz1Lhf4J9Qxoe3DZ2nfe8FGDnvVj7oKjnMY6_237_actual.json
  tests/tzkt_data/tz1Lhf4J9Qxoe3DZ2nfe8FGDnvVj7oKjnMY6_242_actual.json
  tests/tzkt_data/tz1PeZx7FXy7QRuMREGXGxeipb24RsMMzUNe_135_actual.json
  tests/tzkt_data/tz1RV1MBbZMR68tacosb7Mwj6LkbPSUS1er1_242_expected.json
  tests/tzkt_data/tz1S1Aew75hMrPUymqenKfHo8FspppXKpW7h_233_actual.json
  tests/tzkt_data/tz1S8e9GgdZG78XJRB3NqabfWeM37GnhZMWQ_235_expected.json
  tests/tzkt_data/tz1UUgPwikRHW1mEyVZfGYy6QaxrY6Y7WaG5_207_actual.json
  tests/tzkt_data/tz1V4qCyvPKZ5UeqdH14HN42rxvNPQfc9UZg_220_actual.json
  tests/tzkt_data/tz1WnfXMPaNTBmH7DBPwqCWs9cPDJdkGBTZ8_233_expected.json
  tests/tzkt_data/tz1WnfXMPaNTBmH7DBPwqCWs9cPDJdkGBTZ8_74_actual.json
  tests/tzkt_data/tz1YKh8T79LAtWxX29N5VedCSmaZGw9LNVxQ_246_expected.json
  tests/tzkt_data/tz1ZRWFLgT9sz8iFi1VYWPfRYeUvUSFAaDao_201_actual.json
  tests/tzkt_data/tz1ZRWFLgT9sz8iFi1VYWPfRYeUvUSFAaDao_232_expected.json
  tests/tzkt_data/tz1gk3TDbU7cJuiBRMhwQXVvgDnjsxuWhcEA_135_actual.json
Labels: Quality
