Repository tezos-reward-distributor-organization/tezos-reward-distributor, pull requests merged in 2020-10, with the labels that each got.

#281 Add add_argument_api_base_url to configure.py
  src/configure.py
Labels: bug

#282 Optimize tzstats provider
  src/tzstats/tzstats_block_api.py
  src/tzstats/tzstats_reward_provider_helper.py
Labels: enhancement

#288 Fix bug #278
  src/main.py
Labels: bug

#289 Add contibutors and additional payments file
  contribution_payment_history.csv
  contributor_payments.csv
  contributors.csv
Labels: documentation
