Repository tezos-reward-distributor-organization/tezos-reward-distributor, pull requests merged in 2021-01, with the labels that each got.

#343 Admin/Payout plugin message types
  docs/plugins.md
  src/config/yaml_baking_conf_parser.py
  src/pay/batch_payer.py
  src/pay/payment_consumer.py
  src/plugins/email.py
  src/plugins/plugins.py
  src/plugins/telegram.py
  src/plugins/twitter.py
  src/plugins/webhook.py
  src/stats/stats_publisher.py
  tests/test_BakingYamlConfParser.py
Labels: Quality, enhancement

#336 Verbose logging minor tasks: add timing to verbose logs
  src/verbose_logging_helper.py
Labels: documentation & logging

#355 Add missing return parameters
  src/pay/batch_payer.py
Labels: bug

#359 Fix reordering bug causing double transactions to redirected payment addresses
  src/pay/payment_consumer.py
Labels: bug

#358 Dexter fee ratio
  src/Dexter/dexter_utils.py
  src/calc/calculate_phase0.py
  src/calc/calculate_phase3.py
  src/model/reward_log.py
  src/rpc/rpc_reward_api.py
  src/tzkt/tzkt_reward_api.py
  src/tzstats/tzstats_reward_api.py
Labels: bug, enhancement

#353 Add support for delegated KT accounts with active default entrypoint
  fee.ini
  src/pay/batch_payer.py
Labels: critical, enhancement

#362 fix missing internal operation results key in contract payout simulation
  src/pay/batch_payer.py
Labels: bug

#294 [REVIEW_NEEDED] Remove dependency from tezos client
  src/NetworkConfiguration.py
  src/cli/client_manager.py
  src/cli/cmd_manager.py
  src/cli/simple_client_manager.py
  src/cli/wallet_client_manager.py
  src/config/yaml_baking_conf_parser.py
  src/configure.py
  src/launch_common.py
  src/main.py
  src/model/baking_conf.py
  src/pay/batch_payer.py
  src/pay/payment_consumer.py
  src/pay/payment_producer.py
  src/pay_for.py
  src/util/client_utils.py
  tests/test_BakingYamlConfParser.py
  tests/test_rpc_api.py
  tests/test_tzkt_api.py
  tests/test_walletClientManager.py
Labels: critical, enhancement

#364 String-ify replace parameters for Twitter plugin
  src/plugins/twitter.py
Labels: bug
