Repository tezos-reward-distributor-organization/tezos-reward-distributor, pull requests merged in 2021-05, with the labels that each got.

#411 Better Gas Estimations for Oven KT1
  src/calc/calculate_phaseZeroBalance.py
  src/pay/batch_payer.py
  src/pay/payment_producer.py
  tests/integration/test_phases.py
  tests/regression/test_gas_estimation_oven_kt1.py
  tests/utils.py
Labels: critical

#434 make default initial cycle take into account release_override
  src/launch_common.py
  src/pay/payment_producer.py
Labels: bug

#439 Build state graphs automatically
  .github/workflows/ci.yml
  .github/workflows/docs.yml
  docs/fsm/graphviz/config_cycle_state_diagram.png
  docs/fsm/graphviz/draw_state_diagrams.py
  docs/fsm/graphviz/launch_state_diagram.png
  src/fsm/TransitionsFsmBuilder.py
  src/util/config_life_cycle.py
  tests/unit/test_process_life_cycle.py
  tests/unit/test_state_graphs.py
Labels: Quality, documentation & logging
