Repository tezos-reward-distributor-organization/tezos-reward-distributor, pull requests merged in 2021-12, with the labels that each got.

#509 Refactoring + accusation payout toggle
  docs/configuration.rst
  src/calc/calculate_phase0.py
  src/calc/phased_payment_calculator.py
  src/configure.py
  src/model/baking_conf.py
  src/model/reward_provider_model.py
  src/pay/payment_producer.py
  src/rpc/rpc_reward_api.py
  src/tzkt/tzkt_reward_api.py
  src/tzstats/tzstats_api_constants.py
  src/tzstats/tzstats_reward_api.py
  src/tzstats/tzstats_reward_provider_helper.py
  tests/integration/test_phases.py
  tests/integration/test_tzkt_reward_api.py
  tests/integration/tzkt_data/tz1Lhf4J9Qxoe3DZ2nfe8FGDnvVj7oKjnMY6_185_actual.json
  tests/integration/tzkt_data/tz1PeZx7FXy7QRuMREGXGxeipb24RsMMzUNe_135_actual.json
  tests/integration/tzkt_data/tz1RV1MBbZMR68tacosb7Mwj6LkbPSUS1er1_242_expected.json
  tests/integration/tzkt_data/tz1S1Aew75hMrPUymqenKfHo8FspppXKpW7h_233_actual.json
  tests/integration/tzkt_data/tz1S8e9GgdZG78XJRB3NqabfWeM37GnhZMWQ_235_expected.json
  tests/integration/tzkt_data/tz1UUgPwikRHW1mEyVZfGYy6QaxrY6Y7WaG5_207_actual.json
  tests/integration/tzkt_data/tz1V4qCyvPKZ5UeqdH14HN42rxvNPQfc9UZg_220_actual.json
  tests/integration/tzkt_data/tz1WnfXMPaNTBmH7DBPwqCWs9cPDJdkGBTZ8_233_expected.json
  tests/integration/tzkt_data/tz1WnfXMPaNTBmH7DBPwqCWs9cPDJdkGBTZ8_74_actual.json
  tests/integration/tzkt_data/tz1YKh8T79LAtWxX29N5VedCSmaZGw9LNVxQ_246_expected.json
  tests/integration/tzkt_data/tz1ZRWFLgT9sz8iFi1VYWPfRYeUvUSFAaDao_201_actual.json
  tests/integration/tzkt_data/tz1ZRWFLgT9sz8iFi1VYWPfRYeUvUSFAaDao_232_expected.json
  tests/integration/tzkt_data/tz1gk3TDbU7cJuiBRMhwQXVvgDnjsxuWhcEA_135_actual.json
  tests/regression/test_gas_estimation_oven_kt1.py
  tests/unit/test_calculatePhase0.py
  tests/utils.py
Labels: enhancement

#510 Disk size check
  docs/run.rst
  service_add.py
  src/Constants.py
  src/cli/client_manager.py
  src/configure.py
  src/pay/payment_consumer.py
  src/pay/payment_producer.py
  src/pay_for.py
  src/tzkt/tzkt_api.py
  src/tzstats/tzstats_block_api.py
  src/tzstats/tzstats_reward_provider_helper.py
  src/util/csv_payment_file_parser.py
  src/util/disk_is_full.py
  src/util/lock_file.py
  tests/integration/test_tzkt_reward_api.py
  tests/regression/test_baker_validation.py
  tests/regression/test_disk_full.py
  tests/regression/test_tzkt_no_content_request.py
  tests/smoke/test_launch_states.py
  tests/smoke/test_tzkt_api.py
  tests/unit/test_BakingYamlConfParser.py
  tests/unit/test_calculatePhase0.py
  tests/utils.py
Labels: bug, critical

#515 Discord plugin
  docs/plugins.md
  examples/tz1boot1pK9h2BVGXdyvfQSv8kd1LQM6H889.yaml
  src/plugins/discord.py
  src/plugins/telegram.py
Labels: enhancement

#514 Better Stats Submission
  docs/statistics.rst
  src/pay/payment_consumer.py
Labels: enhancement

#523 Update contributors.csv
  contributors.csv
Labels: documentation & logging

#521 Hangzhou2net corrections
  docs/run.rst
  src/Constants.py
  src/launch_common.py
Labels: bug

#524 Final tag fixes before release
  .github/workflows/docker.yml
Labels: critical

#527 Update readme.md
  readme.md
Labels: enhancement, documentation & logging

#526 Return None if no content
  .github/workflows/ci.yml
  src/tzkt/tzkt_api.py
  tests/regression/test_tzkt_no_content_request.py
Labels: bug

#528 --help: use constants to avoid errors with protocol upgrades
  src/Constants.py
  src/cli/client_manager.py
  src/launch_common.py
  src/rpc/rpc_block_api.py
  tests/regression/test_baker_validation.py
  tests/regression/test_gas_estimation_oven_kt1.py
  tests/regression/test_simulate_single_operation.py
  tests/unit/test_BakingYamlConfParser.py
  tests/utils.py
Labels: enhancement

#532 Lock file in config directory
  src/util/lock_file.py
  src/util/process_life_cycle.py
Labels: enhancement

#533 Hotfix/expand user lockfile
  src/stop.py
  src/util/lock_file.py
Labels: bug, critical

#529 Email plugin add features
  docs/plugins.md
  src/plugins/email.py
Labels: enhancement
