Repository tezos-reward-distributor-organization/tezos-reward-distributor, pull requests merged in 2021-02, with the labels that each got.

#363 Prepare for release v8.5
  contribution_payment_history.csv
  examples/tz1boot1pK9h2BVGXdyvfQSv8kd1LQM6H889.yaml
Labels: documentation & logging

#368 Add rewards type to configurator
  src/NetworkConfiguration.py
  src/cli/client_manager.py
  src/config/yaml_baking_conf_parser.py
  src/configure.py
  src/rpc/rpc_reward_api.py
  src/util/address_validator.py
Labels: Quality

#369 Issue 360
  src/pay/batch_payer.py
  src/pay/payment_consumer.py
  src/pay/payment_producer.py
  src/pay/retry_producer.py
  src/util/csv_payment_file_parser.py
  tests/__init__.py
  tests/fee.ini
  tests/test_reports/failed/10.csv
  tests/test_retry_producer.py
Labels: bug, documentation & logging

#373 Fix post-injection fetching of op hash
  src/pay/batch_payer.py
Labels: bug, critical

#370 Improved Documentation for v9
  CODE_OF_CONDUCT.md
  docs/codeofconduct.rst
  docs/conf.py
  docs/configuration.rst
  docs/contributors.rst
  docs/index.rst
  docs/installation.rst
  docs/linuxservice.rst
  docs/paymentaddress.rst
  docs/plugins.md
  docs/run.rst
  docs/tezossigner.rst
  docs/tezossignerdocker.rst
  examples/tz1boot1pK9h2BVGXdyvfQSv8kd1LQM6H889.yaml
  notice.txt
Labels: documentation & logging

#378 Issue 377
  src/cli/client_manager.py
  src/pay/batch_payer.py
Labels: bug

#382 if node url contains 443 token and does not contain http prefix, use …
  src/cli/client_manager.py
Labels: enhancement
