Repository tezos-reward-distributor-organization/tezos-reward-distributor, pull requests merged in 2021-03, with the labels that each got.

#384 Fix internal op parsing
  src/pay/batch_payer.py
Labels: bug

#386 Filter out skipped rewards
  examples/tz1boot1pK9h2BVGXdyvfQSv8kd1LQM6H889.yaml
  src/pay/batch_payer.py
  src/plugins/webhook.py
Labels: bug

#387 Issue log gz
  src/verbose_logging_helper.py
Labels: enhancement

#396 Skip liquidated oven
  src/pay/batch_payer.py
Labels: critical

#398 Replace travis with gh-actions
  .github/pull_request_template.md
  .github/workflows/ci.yml
  .github/workflows/docs.yml
  .travis.yml
  docs/index.rst
  readme.md
  src/pay/batch_payer.py
  tests/test_calculatePhase0.py
  tests/test_retry_producer.py
Labels: Quality

#399 Added contribution details
  contributors.csv
Labels: documentation & logging

#390 application launch states diagram added.
  docs/fsm/application_launch_state_diagram_1.0.pdf
  docs/fsm/application_launch_state_diagram_1.0.pptx
  docs/fsm/comsumer_states_diagram_1.0.pdf
  docs/fsm/comsumer_states_diagram_1.0.pptx
  docs/fsm/producer_states_diagram_1.0.pdf
  docs/fsm/producer_states_diagram_1.0.pptx
Labels: Quality
