Repository tezos-reward-distributor-organization/tezos-reward-distributor, pull requests merged in 2021-07, with the labels that each got.

#451 Hotfix documentation build
  .github/workflows/ci.yml
  .github/workflows/docs.yml
  docs/fsm/graphviz/config_cycle_state_diagram.png
  docs/fsm/graphviz/draw_state_diagrams.py
  docs/fsm/graphviz/launch_state_diagram.png
Labels: documentation & logging

#448 Lower fees and gas limits, double operations per batch
  fee.ini
  src/pay/batch_payer.py
  tests/integration/fee.ini
  tests/regression/test_simulate_single_operation.py
Labels: enhancement

#453 readme.md: fix license text for TzStats
  readme.md
Labels: documentation & logging

#452 contributors.csv: added denver-s
  contributors.csv
Labels: documentation & logging

#456 Hotfix: node.prevalidation.oversized_operation
  src/pay/batch_payer.py
Labels: critical

#447 do not catch up on all late payments by default
  src/configure.py
  src/launch_common.py
  src/pay/payment_producer.py
  src/pay_for.py
  src/util/dir_utils.py
  src/util/process_life_cycle.py
Labels: Quality, enhancement

#457 Remove fee.ini
  fee.ini
  src/main.py
  src/pay/batch_payer.py
  tests/integration/fee.ini
  tests/regression/test_simulate_single_operation.py
Labels: enhancement

#459 CI: fix build-documentation warnings
  docs/codeofconduct.rst
  docs/rundocker.rst
  docs/tezossigner.rst
Labels: documentation & logging

#460 Update readme.md
  readme.md
Labels: documentation & logging

#458 fix CLI argument default values
  docs/run.rst
  src/configure.py
  src/launch_common.py
  src/pay/payment_producer.py
Labels: bug, enhancement

#461 Fix KT1 pay for transfer fee
  src/pay/batch_payer.py
Labels: bug

#463 Resolve invalid branch
  src/pay/batch_payer.py
  tests/integration/test_retry_producer.py
Labels: enhancement

#464 Restyling of doc "How to run TRD"
  docs/run.rst
Labels: documentation & logging

#462 docker tag management
  .github/workflows/docker.yml
Labels: enhancement

#440 fix #429 do not attempt to retry failed payments before INITIAL_CYCLE…
  .gitignore
  src/launch_common.py
  src/pay/payment_producer.py
  src/pay/retry_producer.py
  tests/integration/test_retry_producer.py
Labels: bug

#470 Do not payout accusation rewards when using tzkt
  src/tzkt/tzkt_reward_api.py
  tests/integration/tzkt_data/tz1WnfXMPaNTBmH7DBPwqCWs9cPDJdkGBTZ8_74_actual.json
  tests/integration/tzkt_data/tz1gk3TDbU7cJuiBRMhwQXVvgDnjsxuWhcEA_135_actual.json
Labels: bug
