Repository tezos-reward-distributor-organization/tezos-reward-distributor, pull requests merged in 2021-04, with the labels that each got.

#393 Fsm application lifecycle
  docs/fsm/application_launch_state_diagram_1.0.pdf
  docs/fsm/application_launch_state_diagram_1.0.pptx
  requirements.txt
  src/config/config_parser.py
  src/config/yaml_baking_conf_parser.py
  src/configure.py
  src/fsm/TransitionsFsmBuilder.py
  src/fsm/TransitionsFsmModel.py
  src/fsm/TrdFsmBuilder.py
  src/fsm/TrdFsmModel.py
  src/fsm/__init__.py
  src/fsm/fsm_helper.py
  src/launch_common.py
  src/main.py
  src/model/baking_dirs.py
  src/pay/batch_payer.py
  src/pay/payment_producer.py
  src/util/config_life_cycle.py
  src/util/dir_utils.py
  src/util/process_life_cycle.py
  tests/test_TransitionsFsmBuilder.py
  tests/test_lauch_states.py
  tests/test_rpc_api.py
  tests/test_tzkt_api.py
Labels: Quality

#408 never assume ideal/actual rewards
  docs/configuration.rst
  src/pay/payment_producer.py
Labels: critical

#405 Unit tests refactoring
  .github/workflows/ci.yml
  docs/index.rst
  docs/testing.rst
  src/Constants.py
  src/cli/client_manager.py
  src/launch_common.py
  src/log_config.py
  src/main.py
  src/pay/batch_payer.py
  src/pay/retry_producer.py
  src/rpc/rpc_reward_api.py
  src/stats/stats_publisher.py
  src/tzkt/tzkt_api.py
  src/tzstats/tzstats_reward_provider_helper.py
  tests/integration/fee.ini
  tests/integration/test_phases.py
  tests/integration/test_reports/failed/10.csv
  tests/integration/test_retry_producer.py
  tests/integration/test_tzkt_block_api.py
  tests/integration/test_tzkt_reward_api.py
  tests/integration/tzkt_data/tz1Lhf4J9Qxoe3DZ2nfe8FGDnvVj7oKjnMY6_185_actual.json
  tests/integration/tzkt_data/tz1Lhf4J9Qxoe3DZ2nfe8FGDnvVj7oKjnMY6_237_actual.json
  tests/integration/tzkt_data/tz1Lhf4J9Qxoe3DZ2nfe8FGDnvVj7oKjnMY6_242_actual.json
  tests/integration/tzkt_data/tz1PeZx7FXy7QRuMREGXGxeipb24RsMMzUNe_135_actual.json
  tests/integration/tzkt_data/tz1RV1MBbZMR68tacosb7Mwj6LkbPSUS1er1_242_expected.json
  tests/integration/tzkt_data/tz1S1Aew75hMrPUymqenKfHo8FspppXKpW7h_233_actual.json
  tests/integration/tzkt_data/tz1S8e9GgdZG78XJRB3NqabfWeM37GnhZMWQ_235_expected.json
  tests/integration/tzkt_data/tz1UUgPwikRHW1mEyVZfGYy6QaxrY6Y7WaG5_207_actual.json
  tests/integration/tzkt_data/tz1V4qCyvPKZ5UeqdH14HN42rxvNPQfc9UZg_220_actual.json
  tests/integration/tzkt_data/tz1WnfXMPaNTBmH7DBPwqCWs9cPDJdkGBTZ8_233_expected.json
  tests/integration/tzkt_data/tz1WnfXMPaNTBmH7DBPwqCWs9cPDJdkGBTZ8_74_actual.json
  tests/integration/tzkt_data/tz1YKh8T79LAtWxX29N5VedCSmaZGw9LNVxQ_246_expected.json
  tests/integration/tzkt_data/tz1ZRWFLgT9sz8iFi1VYWPfRYeUvUSFAaDao_201_actual.json
  tests/integration/tzkt_data/tz1ZRWFLgT9sz8iFi1VYWPfRYeUvUSFAaDao_232_expected.json
  tests/integration/tzkt_data/tz1gk3TDbU7cJuiBRMhwQXVvgDnjsxuWhcEA_135_actual.json
  tests/pytest.ini
  tests/readme.md
  tests/regression/dummy_requirements.txt
  tests/regression/test_requirements_installed.py
  tests/regression/test_simulate_single_operation.py
  tests/regression/test_tzkt_no_content_request.py
  tests/smoke/test_launch_states.py
  tests/smoke/test_rpc_api.py
  tests/smoke/test_tzkt_api.py
  tests/test_lauch_states.py
  tests/test_rpc_api.py
  tests/unit/test_BakingYamlConfParser.py
  tests/unit/test_TransitionsFsmBuilder.py
  tests/unit/test_calculatePhase0.py
  tests/unit/test_calculatePhase1.py
  tests/unit/test_calculatePhase2.py
  tests/unit/test_calculatePhase3.py
  tests/unit/test_calculatePhase4.py
  tests/unit/test_calculatePhaseMapping.py
  tests/unit/test_calculatePhaseMerge.py
  tests/unit/test_stats_publisher.py
  tests/unit/test_yamlConfParser.py
  tests/utils.py
Labels: Quality

#418 Webhook type casting
  src/plugins/webhook.py
  tests/regression/test_webhook_send_admin_notification.py
Labels: bug
