Repository tezos-reward-distributor-organization/tezos-reward-distributor, pull requests merged in 2021-08, with the labels that each got.

#415 introduce "self-ideal" rewards like Backerei
  docs/configuration.rst
  src/Constants.py
  src/api/reward_api.py
  src/configure.py
  src/pay/payment_consumer.py
  src/pay/payment_producer.py
  src/rpc/rpc_reward_api.py
  src/tzkt/tzkt_reward_api.py
  src/tzstats/tzstats_reward_api.py
  src/tzstats/tzstats_reward_provider_helper.py
  tests/integration/test_phases.py
  tests/integration/test_tzkt_reward_api.py
  tests/regression/test_gas_estimation_oven_kt1.py
  tests/unit/test_calculatePhase0.py
Labels: enhancement

#471 Better handling of telegram API errors
  src/plugins/telegram.py
Labels: bug

#450 Release: Prepare payments for FLORENCE release, EDO has been skipped
  LICENSE
  contribution_payment_history.csv
  contributors.csv
  docs/conf.py
  src/Constants.py
  src/launch_common.py
Labels: documentation & logging

#473 Fix telegram bool parsing
  src/plugins/telegram.py
Labels: bug

#478 V9.0 transaction documentation
  contribution_payment_history.csv
  contributors.csv
Labels: documentation & logging

#474 Updates for protocol Granada
  .gitignore
  docs/run.rst
  src/Constants.py
  src/NetworkConfiguration.py
  src/api/block_api.py
  src/launch_common.py
  src/pay/batch_payer.py
  src/pay/payment_consumer.py
  src/pay/payment_producer.py
  src/plugins/plugins.py
  src/rpc/rpc_block_api.py
  src/rpc/rpc_reward_api.py
  src/tzkt/tzkt_block_api.py
  src/tzkt/tzkt_reward_api.py
  src/tzstats/tzstats_block_api.py
  tests/integration/test_phases.py
  tests/integration/test_retry_producer.py
  tests/regression/test_baker_validation.py
  tests/regression/test_gas_estimation_oven_kt1.py
  tests/regression/test_simulate_single_operation.py
  tests/smoke/test_rpc_api.py
  tests/unit/test_BakingYamlConfParser.py
  tests/unit/test_calculatePhase0.py
  tests/utils.py
Labels: critical

#479 Fix docker tags
  .github/workflows/docker.yml
Labels: bug

#481 Support all tezos curves
  src/rpc/rpc_block_api.py
Labels: enhancement

#485 Set default reward_data_provider to TzKT
  docs/run.rst
  readme.md
  src/launch_common.py
Labels: enhancement

#492 Minor formatting
  docs/configuration.rst
Labels: documentation & logging

#493 Better calculation of next cycle wait-sleep
  src/pay/payment_producer.py
Labels: bug

#490 Granada: fix rpc rewards if roll snapshot = 15
  src/rpc/rpc_reward_api.py
Labels: bug
