Repository tezos-reward-distributor-organization/tezos-reward-distributor, pull requests merged in 2022-02, with the labels that each got.

#552 fix: pip package installation to return False on error
  docs/conf.py
  src/main.py
  tests/regression/test_requirements_installed.py
Labels: bug

#556 Add possibility to use env variables for smtp_user and smtp_pass
  docs/plugins.md
  src/plugins/email.py
Labels: enhancement

#557 Remove useless file email.ini
  docs/plugins.md
  examples/email.ini
Labels: Quality

#560 Update Docker image to python 3.10.2
  Dockerfile
Labels: Quality

#559 Create a .dokerignore file to minimize Docker image
  .dockerignore
Labels: enhancement
