Repository tezos-reward-distributor-organization/tezos-reward-distributor, pull requests merged in 2022-03, with the labels that each got.

#554 Created new trd-data folder structure, see: baking_dirs.py
  docs/run.rst
  docs/rundocker.rst
  src/Constants.py
  src/configure.py
  src/launch_common.py
  src/log_config.py
  src/model/baking_dirs.py
  src/pay_for.py
  src/stop.py
  src/util/config_life_cycle.py
  src/util/lock_file.py
  tests/utils.py
Labels: bug, enhancement

#562 fixed self.args to args
  src/util/lock_file.py
Labels: bug

#564 fixed expanduser in stop.py
  src/stop.py
Labels: bug

#540 introduce adjusted early payout mode
  docs/configuration.rst
  docs/index.rst
  docs/payouttiming.rst
  docs/run.rst
  src/calc/calculate_phaseMerge.py
  src/calc/calculate_phase_final.py
  src/calc/phased_payment_calculator.py
  src/config/yaml_baking_conf_parser.py
  src/configure.py
  src/launch_common.py
  src/model/reward_log.py
  src/pay/batch_payer.py
  src/pay/payment_consumer.py
  src/pay/payment_producer.py
  src/util/csv_calculation_file_parser.py
  src/util/csv_payment_file_parser.py
  tests/regression/test_gas_estimation_oven_kt1.py
Labels: enhancement

#570 Fix: Fix the service creation tool and stop.py for new default directory or custom configuration directory
  service_add.py
  tezos-reward.service_template
Labels: bug, enhancement

#571 Fix rpc not required when using https endpoint
  service_add.py
  src/cli/client_manager.py
Labels: bug

#575 Adjust requirement.txt package pyyaml and request to new minimum
  requirements.txt
Labels: bug

#572 fix "not in payment log" status in calculation
  requirements.txt
  src/calc/calculate_phase_base.py
  src/calc/calculate_phase_final.py
  src/configure.py
  src/launch_common.py
  src/pay/batch_payer.py
  src/pay/payment_consumer.py
  src/util/csv_calculation_file_parser.py
Labels: bug

#549 Feature/Fix: Add simulated transaction fee to calculations.csv and fix compute logic
  .gitignore
  docs/configuration.rst
  docs/contributors.rst
  docs/plugins.md
  examples/tz1boot1pK9h2BVGXdyvfQSv8kd1LQM6H889.yaml
  requirements.txt
  src/Constants.py
  src/calc/calculate_phase1.py
  src/calc/calculate_phase2.py
  src/calc/calculate_phase3.py
  src/calc/calculate_phase4.py
  src/calc/calculate_phase_base.py
  src/calc/calculate_phase_final.py
  src/calc/phased_payment_calculator.py
  src/config/yaml_baking_conf_parser.py
  src/configure.py
  src/launch_common.py
  src/model/reward_log.py
  src/pay/batch_payer.py
  src/pay/double_payment_check.py
  src/pay/payment_consumer.py
  src/pay/payment_producer.py
  src/pay_for.py
  src/plugins/discord.py
  src/plugins/telegram.py
  src/plugins/twitter.py
  src/plugins/webhook.py
  src/rpc/rpc_reward_api.py
  src/tzstats/tzstats_reward_provider_helper.py
  src/util/csv_calculation_file_parser.py
  src/util/csv_payment_file_parser.py
  src/util/dir_utils.py
  src/util/process_life_cycle.py
  tests/integration/__init__.py
  tests/integration/test_phases.py
  tests/integration/test_reports/failed/10.csv
  tests/integration/test_retry_producer.py
  tests/integration/test_rpc_reward_api.py
  tests/integration/test_tzkt_reward_api.py
  tests/integration/test_tzstats_reward_api.py
  tests/regression/__init__.py
  tests/regression/test_attempt_single_batch.py
  tests/regression/test_gas_estimation_oven_kt1.py
  tests/regression/test_webhook_send_admin_notification.py
  tests/smoke/__init__.py
  tests/unit/__init__.py
  tests/unit/test_calculatePhase3.py
  tests/unit/test_calculatePhase4.py
  tests/unit/test_calculatePhaseMapping.py
  tests/utils.py
Labels: bug, enhancement

#573 Delete pay_for.py
  .github/workflows/ci.yml
  requirements.txt
  src/launch_common.py
  src/pay_for.py
Labels: invalid

#578 Make tests runnable in vscode
  .github/workflows/ci.yml
  .github/workflows/docs.yml
  .gitignore
  docs/contributors.rst
  docs/fsm/graphviz/draw_state_diagrams.py
  docs/img/extension_vscode.png
  docs/img/test_vscode.png
  docs/img/test_vscode_2.png
  docs/img/test_vscode_3.png
  docs/img/test_vscode_4.png
  docs/img/test_vscode_5.png
  docs/img/test_vscode_6.png
  docs/testing.rst
  readme.md
  requirements.txt
  requirements_developers.txt
  tests/__init__.py
  tests/tzkt/simulations/tz1NortRftucvAkD1J58L32EhSVrQEWJCEnB/calculations/201.csv
  tests/unit/test_state_graphs.py
Labels: documentation & logging, Quality

#580 Update Docker image to python 3.10.4
  Dockerfile
Labels: Quality

#579 Documentation/Bugfix: release v10, make tests green and add payment transaction data
  .gitignore
  contribution_payment_history.csv
  src/Constants.py
  src/cli/client_manager.py
  src/main.py
  src/tzkt/tzkt_api.py
  src/tzkt/tzkt_reward_api.py
  src/tzstats/tzstats_reward_provider_helper.py
  src/util/csv_calculation_file_parser.py
  src/util/csv_payment_file_parser.py
  tests/integration/test_retry_producer.py
  tests/integration/test_rpc_reward_api.py
  tests/integration/test_tzkt_reward_api.py
  tests/regression/test_disk_full.py
  tests/regression/test_gas_estimation_oven_kt1.py
  tests/smoke/test_launch_states.py
  tests/smoke/test_rpc_api.py
  tests/smoke/test_tzkt_api.py
  tests/tzkt/simulations/tz1NortRftucvAkD1J58L32EhSVrQEWJCEnB/calculations/201.csv
  tests/unit/test_state_graphs.py
  tests/utils.py
Labels: bug, documentation & logging

#584 Update documentation about fee.ini
  docs/configuration.rst
Labels: documentation & logging

#585 Update contributors.csv
  contributors.csv
Labels: documentation & logging
