Repository tezos-reward-distributor-organization/tezos-reward-distributor, pull requests merged in 2022-12, with the labels that each got.

#631 Refactor: update dry run options and cleanup validator
  docs/run.rst
  src/Constants.py
  src/config/yaml_baking_conf_parser.py
  src/configure.py
  src/launch_common.py
  src/util/args_validator.py
  src/util/parser.py
  src/util/process_life_cycle.py
  tests/regression/test_disk_full.py
  tests/smoke/test_launch_states.py
  tests/smoke/test_rpc_api.py
  tests/smoke/test_tzkt_api.py
  tests/unit/test_args_validator.py
  tests/unit/test_parser.py
  tests/utils.py
Labels: enhancement, Quality

#633 feat: Add pre-commit hooks
  .pre-commit-config.yaml
  docs/installation.rst
  requirements_developers.txt
Labels: Quality

#636 docs: update docs to use octez-x rather than tezos-x for the commands
  docs/paymentaddress.rst
  docs/tezossigner.rst
  src/cli/client_manager.py
Labels: documentation & logging

#638 fix: dry run choices should read correctly
  src/util/parser.py
Labels: bug

#623 Handle simulation errors and mark payments as failed
  src/pay/batch_payer.py
Labels: bug

#643 Release v11
  contribution_payment_history.csv
  src/main.py
Labels: documentation & logging

#644 Mock response block data
  src/rpc/rpc_reward_api.py
  src/tzstats/tzstats_block_api.py
  tests/integration/test_phase.py
  tests/integration/test_rpc_reward_api.py
  tests/utils.py
Labels: Quality

#645 Update RPS for TzKT API
  src/tzkt/tzkt_api.py
Labels: bug

#646 Set gas limit for tz1-to-tz1 transactions to 1001
  src/pay/batch_payer.py
Labels: enhancement

#648 GitHub Actions: update to Node v16
  .github/workflows/ci.yml
Labels: Quality
