Repository tezos-reward-distributor-organization/tezos-reward-distributor, pull requests merged in 2024-02, with the labels that each got.

#691 Update twitter.py
  src/plugins/twitter.py
Labels: bug

#692 remove recursion in logger to prevent too many recursions
  src/verbose_logging_helper.py
Labels: bug

#679 fix #678 - Fix single-shot mode always exiting in error
  src/pay/payment_producer.py
  src/util/process_life_cycle.py
Labels: critical

#695 signals workaround for windows
  src/pay/payment_producer.py
  src/util/process_life_cycle.py
Labels: bug

#689 Prepare-release/v12
  .env.example
  .github/workflows/ci.yml
  .github/workflows/docker.yml
  .github/workflows/docs.yml
  .github/workflows/github-registry.yml
  docs/conf.py
  docs/index.rst
  docs/testing.rst
  readme.md
  src/Constants.py
  src/launch_common.py
  src/util/parser.py
  tests/unit/test_BakingYamlConfParser.py
Labels: documentation & logging
